# Generated by Django 5.0.3 on 2025-08-28 00:52

import django.contrib.auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSpecialist',
            fields=[
                ('id', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('not specified', 'Not Specified')], max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state_or_province', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=20)),
                ('primary_specialization', models.CharField(max_length=30)),
                ('secondary_specialization', models.CharField(max_length=30)),
                ('highest_medical_qualification', models.CharField(max_length=30)),
                ('medical_license_number', models.CharField(max_length=30)),
                ('years_of_experience', models.CharField(max_length=30)),
                ('current_practice_or_hospital', models.CharField(max_length=30)),
                ('professional_bio', models.CharField(max_length=30)),
                ('in_person_consultation', models.BooleanField(default=False)),
                ('surgery', models.BooleanField(default=False)),
                ('emergency_care', models.BooleanField(default=False)),
                ('telemedicine', models.BooleanField(default=False)),
                ('follow_up_care', models.BooleanField(default=False)),
                ('preventive_care', models.BooleanField(default=False)),
                ('weekday_available', models.CharField(choices=[('morning', 'Morning (7am-12pm)'), ('afternoon', 'Afternoon (12pm-5pm)'), ('evening', 'Evening (5pm-10pm)'), ('full-day', 'Full Day (7am-10pm)'), ('not-available', 'Not Available')], max_length=15)),
                ('weekend_available', models.CharField(choices=[('morning', 'Morning (7am-12pm)'), ('afternoon', 'Afternoon (12pm-5pm)'), ('evening', 'Evening (5pm-10pm)'), ('full-day', 'Full Day (7am-10pm)'), ('not-available', 'Not Available')], max_length=15)),
                ('average_appointment_duration', models.IntegerField(choices=[(15, '15 mins'), (30, '30 mins'), (45, '45 mins'), (60, '60 mins'), (90, '90 mins'), (120, '120 mins')])),
                ('profile_photo', models.ImageField(upload_to='./specialist/account')),
                ('government_issued_id', models.ImageField(upload_to='./specialist/account')),
                ('medical_license', models.ImageField(upload_to='./specialist/account')),
                ('medical_degree_certificate', models.ImageField(upload_to='./specialist/account')),
                ('additional_certificate', models.ImageField(upload_to='./specialist/account')),
                ('terms_and_conditions_agreed', models.BooleanField(default=False)),
                ('consent_to_process_data_agreed', models.BooleanField(default=False)),
                ('information_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_no', models.CharField(max_length=15, null=True)),
                ('account_type', models.CharField(choices=[('patient', 'Patient'), ('specialist', 'Specialist')], default='patient', max_length=14)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_alert', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
