# Generated by Django 5.0.3 on 2024-03-30 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_professional_securitymode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
