# Generated by Django 5.0.3 on 2024-03-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='professional',
            name='summary',
            field=models.CharField(max_length=50),
        ),
    ]
